<?xml version="1.0" encoding="utf-8"?><Database Name="StudentDatabase" Class="LinqToSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-4DCB7U6;Initial Catalog=StudentDatabase;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Student_Databse_App.Properties.Settings" SettingsPropertyName="StudentDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student_Table" Member="Student_Tables">
    <Type Name="Student_Table">
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>